name: Voice Of The Harp Limited
favicon: null
layout_spectrum: 0.49067
typography_spectrum: 0.74714
title: Voice Of The Harp Limited
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0b04'
    - '#72512e'
    - '#f0f0f0'
    - '#462c15'
    - '#b69876'
  brandStrength: 0.75
  lightness: 0.9604281440842897
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
