name: Voice Of The Harp Limited
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ac8122'
    - '#d5d6d8'
    - '#4d390b'
  brandStrength: 0.75
  lightness: 0.9604281440842897
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
